services:
  frontend:
    build:
      context: ./Front-end
    container_name: dp1-frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build:
      context: ./Back-end/plg
    container_name: dp1-backend
    ports:
      - "8085:8085"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=defaults
