// Archivo de configuración para la URL base de la API
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

// Configuración centralizada de la API
export const API_CONFIG = {
  BASE_URL: API_BASE_URL,
  ENDPOINTS: {
    SIMULACION: "/simulacion",
    ALMACENES: "/almacenes",
    MEJOR_INDIVIDUO: "/simulacion/mejor",
    INICIAR_SIMULACION: "/simulacion/iniciar",
    REINICIAR_SIMULACION: "/simulacion/reiniciar",
    INFO_SIMULACION: "/simulacion/info",
    ELIMINAR_PAQUETES_FUTUROS: "/simulacion/eliminar-paquetes-futuros",
    CAMBIAR_TIPO_SIMULACION: "/simulacion/cambiar-tipo-simulacion",
    TIPO_SIMULACION_ACTUAL: "/simulacion/tipo-simulacion-actual"
  }
};

// URLs completas para uso directo
export const API_URLS = {
  SIMULACION_BASE: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.SIMULACION}`,
  ALMACENES: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.ALMACENES}`,
  MEJOR_INDIVIDUO: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.MEJOR_INDIVIDUO}`,
  INICIAR_SIMULACION: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.INICIAR_SIMULACION}`,
  REINICIAR_SIMULACION: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.REINICIAR_SIMULACION}`,
  INFO_SIMULACION: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.INFO_SIMULACION}`,
  ELIMINAR_PAQUETES_FUTUROS: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.ELIMINAR_PAQUETES_FUTUROS}`,
  CAMBIAR_TIPO_SIMULACION: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.CAMBIAR_TIPO_SIMULACION}`,
  TIPO_SIMULACION_ACTUAL: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.TIPO_SIMULACION_ACTUAL}`
};
